/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * myNeuralNetworkFunction.c
 *
 * Code generation for function 'myNeuralNetworkFunction'
 *
 */

/* Include files */
#include "myNeuralNetworkFunction.h"
#include <math.h>

/* Function Definitions */
double myNeuralNetworkFunction(const double x1[6])
{
  static const double d_a[10] = {2.9982278942208294,   2.6994769848772333,
                                 -9.5887772831975315,  2.5883209075809361,
                                 -0.23116323303974751, -3.6853650252532781,
                                 -0.28790307452228403, 0.58155827611774047,
                                 2.4033150841162327,   4.1256462379548529};
  static const double b_a[5] = {-2.9904243984376624, 0.51928919785722472,
                                10.611805017699474, -2.199609221306317,
                                0.90831706700444281};
  static const double c_a[5] = {-1.3342647301812991, -3.1488663476331111,
                                0.0011684037776011269, 1.8981976915092809,
                                1.5010133485309036};
  double a;
  double xp1_idx_0;
  double xp1_idx_1;
  int k;
  /* MYNEURALNETWORKFUNCTION neural network simulation function. */
  /*  */
  /*  Auto-generated by MATLAB, 06-Mar-2024 23:10:37. */
  /*   */
  /*  [y1] = myNeuralNetworkFunction(x1) takes these arguments: */
  /*    x = 6xQ matrix, input #1 */
  /*  and returns: */
  /*    y = 1xQ matrix, output #1 */
  /*  where Q is the number of samples. */
  /*  ===== NEURAL NETWORK CONSTANTS ===== */
  /*  Input 1 */
  /*  Layer 1 */
  /*  Layer 2 */
  /*  ===== SIMULATION ======== */
  /*  Dimensions */
  /*  samples */
  /*  Input 1 */
  /*  Remove Constants Input Processing Function */
  /*  ===== MODULE FUNCTIONS ======== */
  /*  Map Minimum and Maximum Input Processing Function */
  xp1_idx_0 = (x1[0] - 0.278) * 0.0501844277720623 + -1.0;
  xp1_idx_1 = x1[5] * 0.00796874756019362 + -1.0;
  /*  Layer 1 */
  /*  Sigmoid Symmetric Transfer Function */
  /*  Layer 2 */
  /*  Sigmoid Positive Transfer Function */
  a = 0.0;
  for (k = 0; k < 5; k++) {
    a += b_a[k] * (2.0 / (exp(-2.0 * (c_a[k] + (d_a[k] * xp1_idx_0 +
                                                d_a[k + 5] * xp1_idx_1))) +
                          1.0) -
                   1.0);
  }
  return 1.0 / (exp(-(a + 0.55810004008388359)) + 1.0);
  /*  Output 1 */
}

/* End of code generation (myNeuralNetworkFunction.c) */
